name: Publish Docker image to Docker Hub

on:
  push:
    tags:
      - 'v*'  # 匹配所有以 v 开头的标签，例如 v1.0.0
    branches:
      - '**'  # 匹配所有分支
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '@push') || startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
